# cleanup
rm -rf obj_dir
rm -f *.vcd

# run Verilator to translate Verilog into C++, including C++ testbench
verilator -IRTL -Wall --cc --trace cpu_pipelined.sv --exe cpu_tb.cpp

# build C++ project via make automatically generated by Verilator
make -j -C obj_dir/ -f Vcpu_pipelined.mk Vcpu_pipelined

# run executable simulation file
echo "\nRunning simulation"
obj_dir/Vcpu_pipelined
echo "\nSimulation completed"

